theme: jekyll-theme-minimal
logo: /assets/img/foto.png
title: Carlos Lorenzon
description: [Apaixonado por tecnologia,  voltada à gestão e automação de processos. 

Formado pela Estácio em  Sistema de Informação,  atuando a 14 anos  na venda e desenvolvimento de softwares.

Facilidade de comunicar e demonstrar as características técnicas e os benefícios dos produtos e serviços da empresa, como também de explorar as oportunidades existentes para resolver outras deficiências e vulnerabilidades do negócio ainda não identificadas pelos clientes.]
