remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
page.title: Carlos Lorenzon
title: Carlos Lorenzon
description: Personal site for articles, useful links, and files

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /blog/tags/:name/
    category: /blog/categories/:name/ 
    post: /blog/:year/:month/:day/:title/


pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: /:num/
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
  category_page_layout: 'category'
  category_page_path: '/categories/:category_name/'
  category_page_title: 'Posts in category :category_name'
